### PR TITLE
Added w3schools and TheOdinProject to the list

### PR DESCRIPTION
**Pull request by vikasganiga05**
Added **w3schools** and **TheOdinProject** to the `free-course-list.md`.

#### Screenshot

image

### CODE REVIEW

**Comment by vinzvinci** [comment]
Hello @vikasganiga05, the w3schools is added, please resolve the conflicts.

**Comment by vikasganiga05** [comment]
> Hello @vikasganiga05, the w3schools is added, please resolve the conflicts.

The conflicts resolved Thank You for letting me know. :pray:

**Review by vinzvinci — APPROVED** [review]
Awesome, thank you for adding this.

**Comment by vikasganiga05** [comment]
Thank You :pray:

**Pull request merged**
